[config]
    url             = "http://localhost:9200"
    username        = ""
    password        = ""
    enabled-indices = ["rating", "transactions", "blocks", "validators", "miniblocks", "rounds", "accounts", "accountshistory", "receipts", "scresults", "accountsesdt", "accountsesdthistory", "epochinfo", "scdeploys", "tokens", "tags", "logs", "delegators", "operations", "esdts"]
    [config.policies]
        enable = true
        indices-with-policy = ["accountsesdthistory", "accountshistory", "blocks", "logs", "miniblocks", "operations", "rounds", "scresults", "transactions"]
